### ISSUE TITLE
ORM error when migrating from v1.0.0b4 to v1.0.0b5

### ISSUE THREAD

**Issue by terhorst** [mealie-recipes/mealie#1818]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

After migrating from b4 to b5, and trying to log in, mealie-api throws the following error:

```
  File "/app/mealie/repos/repository_generic.py", line 143, in get_one
    return eff_schema.from_orm(result)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/pydantic/main.py", line 575, in from_orm
    obj = {ROOT_KEY: obj} if cls.__custom_root_type__ else cls._decompose_class(obj)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/pydantic/main.py", line 725, in _decompose_class
    return cls.__config__.getter_dict(obj)
  File "/app/mealie/schema/user/user.py", line 117, in getter_dict
    "group": ormModel.group.name,
AttributeError: 'NoneType' object has no attribute 'name'
```

It seems that the `User.group` attribute can be `None`, but the code does not check for this before trying to access `group.name`. 

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
Hey, sorry for the late reply, couple of questions

1. When is this error being thrown?
2. Would you be willing the share your SQLite database file or your export file privately?

There's not really a circumstance that a user shouldn't have a group, so i'm a bit stumped on this one.
